# Generated by Django 3.1.1 on 2020-12-28 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0019_auto_20201228_1128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
