# Generated by Django 3.1.1 on 2020-12-28 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0023_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='student',
        ),
    ]
